// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.19;

error CALLER_NOT_CONTROLLER();
error CALLER_NOT_OWNER();
error CALLER_NOT_MESSENGER();
error CHAIN_NOT_SUPPORTED();
error CALL_MOS_FAIL();
error WITHDRAW_ETH_FAIL();
error VAULT_NOT_EXISTS();
error CALLER_NOT_KASHPOOL();
error INSUFFICIENT_VAULT_FUNDS();
